export const LOAD_DEVICES_SUCCESS = 'LOAD_DEVICES_SUCCESS';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const DESTROY_DEVICE_SUCCESS = 'DESTROY_DEVICE_SUCCESS';